import React, { useState } from 'react';
import { Upload, Download, X, AlertCircle, CheckCircle2, FileSpreadsheet } from 'lucide-react';
import * as XLSX from 'xlsx';

const ImportVocabularyModal = ({ articleId, onClose, onImportSuccess }) => {
  const [file, setFile] = useState(null);
  const [parsing, setParsing] = useState(false);
  const [importing, setImporting] = useState(false);
  const [parsedData, setParsedData] = useState([]);
  const [errors, setErrors] = useState([]);
  const [previewMode, setPreviewMode] = useState(false);

  // Download Excel template
  const downloadTemplate = () => {
    const template = [
      {
        'Word *': 'example',
        'Phonetic': '/ɪɡˈzæmpl/',
        'Part of Speech': 'noun',
        'Vietnamese *': 'ví dụ',
        'Definition': 'a thing characteristic of its kind',
        'Example Sentence': 'This is an example sentence.',
        'Example Vietnamese': 'Đây là một câu ví dụ.',
        'Level *': 'BEGINNER',
        'Notes': 'Important word'
      },
      {
        'Word *': 'achieve',
        'Phonetic': '/əˈtʃiːv/',
        'Part of Speech': 'verb',
        'Vietnamese *': 'đạt được',
        'Definition': 'successfully reach a goal',
        'Example Sentence': 'She achieved her dreams.',
        'Example Vietnamese': 'Cô ấy đã đạt được ước mơ.',
        'Level *': 'INTERMEDIATE',
        'Notes': ''
      },
      {
        'Word *': 'ubiquitous',
        'Phonetic': '/juːˈbɪkwɪtəs/',
        'Part of Speech': 'adjective',
        'Vietnamese *': 'có mặt khắp nơi',
        'Definition': 'present everywhere',
        'Example Sentence': 'Smartphones are ubiquitous.',
        'Example Vietnamese': 'Điện thoại thông minh có mặt khắp nơi.',
        'Level *': 'ADVANCED',
        'Notes': ''
      }
    ];

    const ws = XLSX.utils.json_to_sheet(template);
    
    // Set column widths
    ws['!cols'] = [
      { wch: 15 }, // Word
      { wch: 15 }, // Phonetic
      { wch: 15 }, // Part of Speech
      { wch: 20 }, // Vietnamese
      { wch: 40 }, // Definition
      { wch: 40 }, // Example Sentence
      { wch: 40 }, // Example Vietnamese
      { wch: 15 }, // Level
      { wch: 30 }  // Notes
    ];

    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Vocabulary Template');
    XLSX.writeFile(wb, 'vocabulary_template.xlsx');
  };

  // Parse Excel file
  const handleFileChange = async (e) => {
    const selectedFile = e.target.files[0];
    if (!selectedFile) return;

    if (!selectedFile.name.match(/\.(xlsx|xls)$/)) {
      alert('Vui lòng chọn file Excel (.xlsx hoặc .xls)');
      return;
    }

    setFile(selectedFile);
    setParsing(true);
    setErrors([]);
    setParsedData([]);

    try {
      const data = await selectedFile.arrayBuffer();
      const workbook = XLSX.read(data, { type: 'array' });
      const firstSheet = workbook.Sheets[workbook.SheetNames[0]];
      const jsonData = XLSX.utils.sheet_to_json(firstSheet);

      // Validate and transform data
      const validationErrors = [];
      const transformedData = [];

      jsonData.forEach((row, index) => {
        const rowNum = index + 2; // Excel row number (starts at 2 after header)
        const vocab = {};

        // Required fields
        if (!row['Word *'] || !row['Word *'].toString().trim()) {
          validationErrors.push(`Dòng ${rowNum}: Thiếu Word`);
          return;
        }
        vocab.word = row['Word *'].toString().trim();

        if (!row['Vietnamese *'] || !row['Vietnamese *'].toString().trim()) {
          validationErrors.push(`Dòng ${rowNum}: Thiếu Vietnamese`);
          return;
        }
        vocab.vietnamese = row['Vietnamese *'].toString().trim();

        if (!row['Level *'] || !['BEGINNER', 'INTERMEDIATE', 'ADVANCED'].includes(row['Level *'].toString().trim().toUpperCase())) {
          validationErrors.push(`Dòng ${rowNum}: Level không hợp lệ (phải là BEGINNER, INTERMEDIATE, hoặc ADVANCED)`);
          return;
        }
        vocab.level = row['Level *'].toString().trim().toUpperCase();

        // Optional fields
        vocab.phonetic = row['Phonetic'] ? row['Phonetic'].toString().trim() : '';
        vocab.partOfSpeech = row['Part of Speech'] ? row['Part of Speech'].toString().trim() : '';
        vocab.definition = row['Definition'] ? row['Definition'].toString().trim() : '';
        vocab.exampleSentence = row['Example Sentence'] ? row['Example Sentence'].toString().trim() : '';
        vocab.exampleVietnamese = row['Example Vietnamese'] ? row['Example Vietnamese'].toString().trim() : '';
        vocab.notes = row['Notes'] ? row['Notes'].toString().trim() : '';
        vocab.approved = false;
        vocab.autoGenerated = false;

        transformedData.push(vocab);
      });

      if (validationErrors.length > 0) {
        setErrors(validationErrors);
      } else {
        setParsedData(transformedData);
        setPreviewMode(true);
      }
    } catch (error) {
      console.error('Error parsing Excel:', error);
      setErrors(['Không thể đọc file Excel. Vui lòng kiểm tra định dạng file.']);
    } finally {
      setParsing(false);
    }
  };

  // Import vocabularies
  const handleImport = async () => {
    if (parsedData.length === 0) return;

    setImporting(true);
    let successCount = 0;
    let failCount = 0;

    try {
      // Import từng vocabulary một
      for (const vocab of parsedData) {
        try {
          const response = await fetch(
            `http://localhost:8080/api/admin/articles/${articleId}/vocabularies`,
            {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${localStorage.getItem('accessToken') || localStorage.getItem('token') || localStorage.getItem('adminToken')}`
              },
              body: JSON.stringify(vocab)
            }
          );

          if (response.ok) {
            successCount++;
          } else {
            failCount++;
            console.error(`Failed to import: ${vocab.word}`);
          }
        } catch (error) {
          failCount++;
          console.error(`Error importing ${vocab.word}:`, error);
        }
      }

      if (successCount > 0) {
        alert(`✅ Import thành công ${successCount}/${parsedData.length} từ vựng!${failCount > 0 ? `\n❌ ${failCount} từ bị lỗi.` : ''}`);
        onImportSuccess();
        onClose();
      } else {
        alert('❌ Không thể import từ vựng nào. Vui lòng thử lại.');
      }
    } catch (error) {
      console.error('Error importing:', error);
      alert('❌ Lỗi khi import. Vui lòng thử lại.');
    } finally {
      setImporting(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-lg shadow-xl max-w-4xl w-full max-h-[90vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="px-6 py-4 border-b border-gray-200 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <FileSpreadsheet className="text-green-600" size={24} />
            <div>
              <h3 className="text-xl font-bold text-gray-900">Import Vocabulary từ Excel</h3>
              <p className="text-sm text-gray-600">Thêm hàng loạt vocabulary từ file Excel</p>
            </div>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-lg">
            <X size={20} />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          {!previewMode ? (
            // Upload Section
            <div className="space-y-6">
              {/* Download Template */}
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                <div className="flex items-start gap-3">
                  <AlertCircle className="text-blue-600 flex-shrink-0 mt-0.5" size={20} />
                  <div className="flex-1">
                    <h4 className="font-medium text-blue-900 mb-2">📥 Bước 1: Download Template</h4>
                    <p className="text-sm text-blue-800 mb-3">
                      Tải file Excel mẫu, điền thông tin vocabulary, sau đó upload lại.
                    </p>
                    <button
                      onClick={downloadTemplate}
                      className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
                    >
                      <Download size={18} />
                      Download Template Excel
                    </button>
                  </div>
                </div>
              </div>

              {/* Instructions */}
              <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
                <h4 className="font-medium text-gray-900 mb-3">📋 Hướng dẫn điền file Excel:</h4>
                <ul className="space-y-2 text-sm text-gray-700">
                  <li className="flex items-start gap-2">
                    <span className="text-red-500 font-bold">*</span>
                    <div>
                      <strong>Word *</strong> (bắt buộc): Từ vựng tiếng Anh
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-gray-400">○</span>
                    <div>
                      <strong>Phonetic</strong>: Phiên âm (VD: /həˈloʊ/)
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-gray-400">○</span>
                    <div>
                      <strong>Part of Speech</strong>: Từ loại (noun, verb, adjective...)
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-red-500 font-bold">*</span>
                    <div>
                      <strong>Vietnamese *</strong> (bắt buộc): Nghĩa tiếng Việt
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-gray-400">○</span>
                    <div>
                      <strong>Definition</strong>: Định nghĩa tiếng Anh
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-gray-400">○</span>
                    <div>
                      <strong>Example Sentence</strong>: Câu ví dụ tiếng Anh
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-gray-400">○</span>
                    <div>
                      <strong>Example Vietnamese</strong>: Câu ví dụ tiếng Việt
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-red-500 font-bold">*</span>
                    <div>
                      <strong>Level *</strong> (bắt buộc): BEGINNER, INTERMEDIATE, hoặc ADVANCED
                    </div>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-gray-400">○</span>
                    <div>
                      <strong>Notes</strong>: Ghi chú thêm
                    </div>
                  </li>
                </ul>
              </div>

              {/* Upload Area */}
              <div className="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center hover:border-blue-500 transition-colors">
                <Upload className="mx-auto mb-4 text-gray-400" size={48} />
                <h4 className="text-lg font-medium text-gray-900 mb-2">📤 Bước 2: Upload File Excel</h4>
                <p className="text-sm text-gray-600 mb-4">
                  Kéo thả file hoặc click để chọn file
                </p>
                <input
                  type="file"
                  accept=".xlsx,.xls"
                  onChange={handleFileChange}
                  className="hidden"
                  id="excel-upload"
                  disabled={parsing}
                />
                <label
                  htmlFor="excel-upload"
                  className="inline-flex items-center gap-2 px-6 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 cursor-pointer transition-colors"
                >
                  {parsing ? (
                    <>
                      <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                      Đang xử lý...
                    </>
                  ) : (
                    <>
                      <Upload size={20} />
                      Chọn file Excel
                    </>
                  )}
                </label>
                {file && (
                  <p className="text-sm text-gray-600 mt-3">
                    Đã chọn: <strong>{file.name}</strong>
                  </p>
                )}
              </div>

              {/* Errors */}
              {errors.length > 0 && (
                <div className="bg-red-50 border border-red-200 rounded-lg p-4">
                  <div className="flex items-start gap-3">
                    <AlertCircle className="text-red-600 flex-shrink-0 mt-0.5" size={20} />
                    <div className="flex-1">
                      <h4 className="font-medium text-red-900 mb-2">❌ Lỗi trong file Excel:</h4>
                      <ul className="space-y-1 text-sm text-red-800">
                        {errors.map((error, idx) => (
                          <li key={idx}>• {error}</li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </div>
              )}
            </div>
          ) : (
            // Preview Section
            <div className="space-y-4">
              <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                <div className="flex items-center gap-3">
                  <CheckCircle2 className="text-green-600" size={24} />
                  <div>
                    <h4 className="font-medium text-green-900">
                      ✅ Đã phân tích thành công!
                    </h4>
                    <p className="text-sm text-green-800">
                      Tìm thấy {parsedData.length} từ vựng. Xem trước và xác nhận import.
                    </p>
                  </div>
                </div>
              </div>

              {/* Preview Table */}
              <div className="border border-gray-200 rounded-lg overflow-x-auto">
                <table className="min-w-full divide-y divide-gray-200">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">#</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Word</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Vietnamese</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Level</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Phonetic</th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {parsedData.map((vocab, idx) => (
                      <tr key={idx} className="hover:bg-gray-50">
                        <td className="px-4 py-3 text-sm text-gray-500">{idx + 1}</td>
                        <td className="px-4 py-3 text-sm font-medium text-gray-900">{vocab.word}</td>
                        <td className="px-4 py-3 text-sm text-gray-700">{vocab.vietnamese}</td>
                        <td className="px-4 py-3">
                          <span className={`px-2 py-1 text-xs rounded ${
                            vocab.level === 'BEGINNER' ? 'bg-green-100 text-green-800' :
                            vocab.level === 'INTERMEDIATE' ? 'bg-blue-100 text-blue-800' :
                            'bg-purple-100 text-purple-800'
                          }`}>
                            {vocab.level}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-sm text-gray-500 italic">{vocab.phonetic || '-'}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-gray-200 flex justify-between items-center">
          <button
            onClick={onClose}
            disabled={importing}
            className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
          >
            Hủy
          </button>
          
          {previewMode && (
            <div className="flex gap-3">
              <button
                onClick={() => {
                  setPreviewMode(false);
                  setFile(null);
                  setParsedData([]);
                }}
                disabled={importing}
                className="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition-colors"
              >
                ← Quay lại
              </button>
              <button
                onClick={handleImport}
                disabled={importing || parsedData.length === 0}
                className="flex items-center gap-2 px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                {importing ? (
                  <>
                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                    Đang import...
                  </>
                ) : (
                  <>
                    <CheckCircle2 size={20} />
                    Import {parsedData.length} từ vựng
                  </>
                )}
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ImportVocabularyModal;
